branches:
    only: 
    - master

language: python
    - "3.6"

install: 
    - pip install -r requirements.txt

script:
    - pytest tests.py

notifications:
  email:
    recipients:
      - tomekterka@loves.dicksinhisan.us
    on_success: never 
    on_failure: always 