branches:
    only: 
    - master

sudo: required

language: python

python:
    - "3.6"

install: 
    - pip install -r requirements.txt
    - sudo chmod a+w /etc/hosts
    - sudo echo "185.31.160.192  karachan.org" >> /etc/hosts

script:
    - pytest tests.py -s

notifications:
  email:
    recipients:
      - tomekterka@loves.dicksinhisan.us
    on_success: never 
    on_failure: always 